version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_RUN_HOST=0.0.0.0
    depends_on:
      - db
    volumes:
      - ./app:/app/app
    networks:
      - vulnbook-network
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=vulnbook
      - POSTGRES_PASSWORD=vulnbook
      - POSTGRES_DB=vulnbook
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - vulnbook-network
networks:
  vulnbook-network:
    driver: bridge
volumes:
  pgdata: